In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder


1. Read datasets, and preprocessing

In [4]:
data = pd.read_csv('Dataset/Iris.csv')

standartScaler = StandardScaler()
x = data.drop(['Species'], axis=1)
y = data['Species']
x = standartScaler.fit_transform(x)
scaler = LabelEncoder()
y = scaler.fit_transform(y)

intercept = np.ones((x.shape[0], 1))
x = np.concatenate((intercept, x), axis=1)
print(x)
# print(x)

# print(y)

print(data.shape)

[[ 1.00000000e+00 -1.72054204e+00 -9.00681170e-01  1.03205722e+00
  -1.34127240e+00 -1.31297673e+00]
 [ 1.00000000e+00 -1.69744751e+00 -1.14301691e+00 -1.24957601e-01
  -1.34127240e+00 -1.31297673e+00]
 [ 1.00000000e+00 -1.67435299e+00 -1.38535265e+00  3.37848329e-01
  -1.39813811e+00 -1.31297673e+00]
 [ 1.00000000e+00 -1.65125846e+00 -1.50652052e+00  1.06445364e-01
  -1.28440670e+00 -1.31297673e+00]
 [ 1.00000000e+00 -1.62816394e+00 -1.02184904e+00  1.26346019e+00
  -1.34127240e+00 -1.31297673e+00]
 [ 1.00000000e+00 -1.60506942e+00 -5.37177559e-01  1.95766909e+00
  -1.17067529e+00 -1.05003079e+00]
 [ 1.00000000e+00 -1.58197489e+00 -1.50652052e+00  8.00654259e-01
  -1.34127240e+00 -1.18150376e+00]
 [ 1.00000000e+00 -1.55888037e+00 -1.02184904e+00  8.00654259e-01
  -1.28440670e+00 -1.31297673e+00]
 [ 1.00000000e+00 -1.53578584e+00 -1.74885626e+00 -3.56360566e-01
  -1.34127240e+00 -1.31297673e+00]
 [ 1.00000000e+00 -1.51269132e+00 -1.14301691e+00  1.06445364e-01
  -1.28440670e+00 -1.4444

2. Split datasets into training and test sets

In [5]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.5, random_state=42)

print(x_train)

print(y_train)

[[ 1.00000000e+00  2.19397978e-01 -5.37177559e-01 -1.24957601e-01
   4.21564419e-01  3.96171883e-01]
 [ 1.00000000e+00  1.69744751e+00  4.32165405e-01  8.00654259e-01
   9.33355755e-01  1.44795564e+00]
 [ 1.00000000e+00 -4.96532266e-01 -4.16009689e-01 -1.74477836e+00
   1.37235899e-01  1.33225943e-01]
 [ 1.00000000e+00 -1.60506942e+00 -5.37177559e-01  1.95766909e+00
  -1.17067529e+00 -1.05003079e+00]
 [ 1.00000000e+00  4.27248694e-01 -1.02184904e+00 -1.74477836e+00
  -2.60824029e-01 -2.61192967e-01]
 [ 1.00000000e+00  8.42950125e-01  6.74501145e-01 -8.19166497e-01
   8.76490051e-01  9.22063763e-01]
 [ 1.00000000e+00 -5.88910362e-01 -1.02184904e+00  5.69251294e-01
  -1.34127240e+00 -1.31297673e+00]
 [ 1.00000000e+00 -9.12233697e-01 -1.02184904e+00  3.37848329e-01
  -1.45500381e+00 -1.31297673e+00]
 [ 1.00000000e+00  1.27019882e-01 -4.16009689e-01 -1.51337539e+00
   2.35044910e-02 -1.29719997e-01]
 [ 1.00000000e+00  5.77363100e-02  1.03800476e+00 -1.24957601e-01
   7.05892939e-01  6.5911

3. Using softmax to solve this problem

In [6]:
N = x_train.shape[0]
k = 3 
d = data.shape[1]
def compute_one_hot(y_train, k):

    one_hot = np.zeros((len(y_train), k))
    one_hot[np.arange(len(y_train)), y_train] = 1
    return one_hot

y_one_hot = compute_one_hot(y_train, k)

#print(y_one_hot)


print(d)

6


In [7]:
weights = 0.01 * np.random.randn(d, k)
print('theta:\n', weights)
print(x_train.shape)
print(weights.shape)

theta:
 [[-0.00677315 -0.00386342 -0.00455226]
 [ 0.00219527  0.01168919 -0.00746646]
 [-0.00557645 -0.00114476  0.00383354]
 [ 0.00447623 -0.00376874 -0.00242176]
 [ 0.00098011  0.0063392  -0.00286992]
 [-0.00376097 -0.01187631  0.01248759]]
(75, 6)
(6, 3)


In [8]:
learing_rate = 0.01
epochs = 1000
losses = []

for epoch in range(epochs):

    # Probability of each class
    z = x_train.dot(weights)
    max = np.max(z, axis = 1, keepdims=True)
    exp = np.exp(z - max)
    probability = exp / np.sum(exp,axis = 1,keepdims=True)

    # Loss 

    loss = -(y_one_hot * np.log(probability)).sum()
    losses.append(loss)

    # Gradient

    gradient = probability - y_one_hot

    dTheta = x_train.T.dot(gradient)

    # Update weights
    weights -= learing_rate * dTheta
    

In [ ]:
prediction = x_test.dot(weights)

print(prediction)
predicted_class = np.argmax(prediction, axis=1)

print("Predicted class: ", predicted_class)

print("Actual class: ", y_test)

accuracy = np.mean(predicted_class == y_test) * 100

print("Accuracy: ", accuracy)

[[ -3.77882993   5.27283026  -1.50692574]
 [ 12.45623893   6.16504868 -18.6487961 ]
 [-18.37231925   4.73204345  13.63022672]
 [ -4.30947474   4.40707845  -0.11158315]
 [ -6.29929592   5.82429138   0.45949937]
 [ 10.83566035   5.58477395 -16.44429964]
 [ -0.35150392   4.61921267  -4.28381267]
 [-13.24225933   1.1825032   12.04937751]
 [ -6.59659228   6.33887037   0.2443373 ]
 [ -2.67984525   4.35199485  -1.6843188 ]
 [ -9.09560382   2.50229275   6.58058278]
 [ 13.07035481   6.77426462 -19.86662557]
 [ 11.7927059    5.38109289 -17.19734745]
 [ 13.2289937    6.92867995 -20.18061801]
 [ 13.95300461   5.32037786 -19.29914943]
 [ -2.90794254   5.32037136  -2.43221359]
 [-11.41510941   3.18004309   8.22318501]
 [ -1.83090695   5.2354119   -3.41669376]
 [ -1.92917363   5.64502388  -3.7309642 ]
 [-13.24762688   1.77206139  11.4684716 ]
 [ 12.24117012   5.35475886 -17.61576692]
 [ -8.90990433   1.50424615   7.39796475]
 [ 11.76767274   5.39904215 -17.18966874]
 [-12.6305893    2.07757945  10.54